package com.videhub.service

import android.content.Context
import android.os.Environment
import androidx.core.app.NotificationCompat
import androidx.core.app.NotificationManagerCompat
import androidx.work.CoroutineWorker
import androidx.work.WorkerParameters
import com.videhub.data.AppDatabase
import com.videhub.data.entity.DownloadedPlaylistEntity
import com.videhub.data.entity.DownloadedPlaylistVideoCrossRef
import com.videhub.data.entity.DownloadedVideoEntity
import com.videhub.extractor.ExtractorHelper
import java.io.File
import java.io.FileOutputStream
import java.net.HttpURLConnection
import java.net.URL
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

class PlaylistDownloadWorker(
    appContext: Context,
    workerParams: WorkerParameters
) : CoroutineWorker(appContext, workerParams) {

    override suspend fun doWork(): Result = withContext(Dispatchers.IO) {
        val videoUrl = inputData.getString("videoUrl") ?: return@withContext Result.failure()
        val playlistId = inputData.getString("playlistId") ?: return@withContext Result.failure()
        val playlistTitle = inputData.getString("playlistTitle") ?: "Playlist"
        val playlistThumbnail = inputData.getString("playlistThumbnail") ?: ""
        val videoTitle = inputData.getString("videoTitle") ?: "Video"
        val notificationId = videoUrl.hashCode()

        try {
            val db = AppDatabase.getDatabase(applicationContext)

            // Insert Playlist Entity with local thumbnail
            val localPlaylistThumb = if (playlistThumbnail.isNotBlank()) {
                com.videhub.utils.ThumbnailDownloader.downloadThumbnail(
                    applicationContext,
                    playlistId,
                    playlistThumbnail
                ) ?: playlistThumbnail
            } else playlistThumbnail

            db.downloadedPlaylistDao().insertPlaylist(
                DownloadedPlaylistEntity(playlistId, playlistTitle, localPlaylistThumb)
            )

            val isAlreadyDownloaded = db.downloadedVideoDao().isVideoDownloaded(videoUrl)
            if (isAlreadyDownloaded) {
                // Just link it
                db.downloadedPlaylistDao().insertPlaylistVideoCrossRef(
                    DownloadedPlaylistVideoCrossRef(playlistId, videoUrl)
                )
                return@withContext Result.success()
            }

            // Show Notification
            val notificationManager = NotificationManagerCompat.from(applicationContext)
            if (androidx.core.app.ActivityCompat.checkSelfPermission(applicationContext, android.Manifest.permission.POST_NOTIFICATIONS) == android.content.pm.PackageManager.PERMISSION_GRANTED) {
                val notification = NotificationCompat.Builder(applicationContext, "download_channel")
                    .setContentTitle("Downloading: $videoTitle")
                    .setContentText("Part of $playlistTitle")
                    .setSmallIcon(android.R.drawable.stat_sys_download)
                    .setProgress(100, 0, true)
                    .build()
                notificationManager.notify(notificationId, notification)
            }

            // Extract fresh info
            val streamInfo = ExtractorHelper.getStreamInfo(videoUrl)
            val videoStream = streamInfo?.videoStreams?.filter { !it.content.isNullOrBlank() && !it.isVideoOnly }?.maxByOrNull { it.height ?: 0 }
                ?: return@withContext Result.failure()

            val streamUrl = videoStream.content ?: return@withContext Result.failure()
            val res = videoStream.resolution ?: "unknown"
            val suffix = "${res}.mp4"
            val safeTitle = videoTitle.replace(Regex("[\\\\/:*?\"<>|]"), "_")
            val finalFileName = "${safeTitle}_$suffix"
            val tempDir = applicationContext.getExternalFilesDir(Environment.DIRECTORY_DOWNLOADS)
            val finalFile = File(tempDir, finalFileName)

            // Download
            val urlObj = URL(streamUrl)
            val connection = urlObj.openConnection() as HttpURLConnection
            connection.connectTimeout = 30000
            connection.readTimeout = 30000
            connection.connect()
            
            if (connection.responseCode != HttpURLConnection.HTTP_OK) {
                return@withContext Result.retry()
            }

            val inputStream = connection.inputStream
            val outputStream = FileOutputStream(finalFile)
            val buffer = ByteArray(8 * 1024)
            var bytesRead: Int
            while (inputStream.read(buffer).also { bytesRead = it } != -1) {
                outputStream.write(buffer, 0, bytesRead)
            }
            outputStream.flush()
            outputStream.close()
            inputStream.close()

            // Save Captions
            var savedLyrics: String? = null
            try {
                val nativeSub = streamInfo.subtitles?.find { it.isAutoGenerated == false && it.languageTag == "en" }?.content 
                    ?: streamInfo.subtitles?.find { it.isAutoGenerated == false }?.content
                val enSub = streamInfo.subtitles?.find { it.isAutoGenerated == true && it.languageTag == "en" }?.content 
                    ?: streamInfo.subtitles?.find { it.isAutoGenerated == true }?.content

                val subArr = org.json.JSONArray()
                streamInfo.subtitles?.forEach { s ->
                    val o = org.json.JSONObject()
                    o.put("url", s.content)
                    o.put("languageTag", s.languageTag)
                    o.put("isAutoGenerated", s.isAutoGenerated)
                    subArr.put(o)
                }

                savedLyrics = com.videhub.ui.components.LiveCaptionsManager.downloadAndSaveCaptions(
                    context = applicationContext,
                    videoId = videoUrl,
                    nativeUrl = nativeSub,
                    englishUrl = enSub,
                    artist = streamInfo.uploaderName ?: "",
                    title = videoTitle,
                    description = streamInfo.description?.content,
                    subtitlesJson = subArr.toString()
                )
            } catch (e: Exception) {}

            // Save to DB
            val originalThumbUrl = streamInfo.thumbnails.firstOrNull()?.url ?: ""
            val localThumbPath = com.videhub.utils.ThumbnailDownloader.downloadThumbnail(
                applicationContext,
                videoUrl,
                originalThumbUrl
            )
            db.downloadedVideoDao().insertDownload(
                DownloadedVideoEntity(
                    videoId = videoUrl,
                    title = videoTitle,
                    thumbnailUrl = localThumbPath ?: originalThumbUrl,
                    channelName = streamInfo.uploaderName ?: "",
                    viewCount = streamInfo.viewCount ?: 0L,
                    uploadDate = streamInfo.textualUploadDate ?: "",
                    fileName = finalFileName,
                    isAudioOnly = false,
                    downloadedAt = System.currentTimeMillis(),
                    lyrics = savedLyrics
                )
            )

            // Link to playlist
            db.downloadedPlaylistDao().insertPlaylistVideoCrossRef(
                DownloadedPlaylistVideoCrossRef(playlistId, videoUrl)
            )

            notificationManager.cancel(notificationId)
            Result.success()
        } catch (e: Exception) {
            e.printStackTrace()
            if (e is java.net.SocketException || e is java.io.IOException) {
                Result.retry()
            } else {
                Result.failure()
            }
        }
    }
}
