package com.videhub.ui.components

import org.schabi.newpipe.extractor.stream.SubtitlesStream
import java.util.Locale

data class CaptionTrack(
    val languageTag: String,
    val displayName: String,
    val url: String,
    val isAutoGenerated: Boolean = false
) {
    companion object {
        fun fromSubtitlesStream(sub: SubtitlesStream): CaptionTrack? {
            val streamUrl = (sub.content.takeIf { !it.isNullOrBlank() } ?: sub.url).orEmpty()
            val tag = sub.languageTag
            if (streamUrl.isBlank() || tag.isNullOrBlank()) return null

            val display = try {
                val loc = Locale.forLanguageTag(tag)
                val name = loc.getDisplayName(loc).ifBlank { loc.displayLanguage }
                (if (name.isNotBlank()) name else (sub.displayLanguageName ?: tag)).replaceFirstChar {
                    if (it.isLowerCase()) it.titlecase(Locale.getDefault()) else it.toString()
                }
            } catch (e: Exception) {
                sub.displayLanguageName ?: tag
            }

            return CaptionTrack(
                languageTag = tag,
                displayName = display,
                url = streamUrl,
                isAutoGenerated = sub.isAutoGenerated
            )
        }

        fun extractTracks(subtitles: List<SubtitlesStream>?): List<CaptionTrack> {
            if (subtitles.isNullOrEmpty()) return emptyList()
            val direct = subtitles.mapNotNull { fromSubtitlesStream(it) }
            return buildAutoTranslatedTracks(direct)
        }

        fun buildAutoTranslatedTracks(baseTracks: List<CaptionTrack>): List<CaptionTrack> {
            if (baseTracks.isEmpty()) return emptyList()
            // Find best base track to translate from (preferably manual en, or auto en, or first available timedtext track)
            val baseTrack = baseTracks.find { it.languageTag.startsWith("en", ignoreCase = true) && !it.isAutoGenerated }
                ?: baseTracks.find { it.languageTag.startsWith("en", ignoreCase = true) }
                ?: baseTracks.firstOrNull { it.url.contains("timedtext") || it.url.contains("youtube.com") }
                ?: baseTracks.first()

            if (!baseTrack.url.contains("timedtext") && !baseTrack.url.contains("youtube.com")) {
                return baseTracks
            }

            val existingLangs = baseTracks.map { it.languageTag.lowercase() }.toSet()

            val popularTranslations = listOf(
                "hi" to "Hindi",
                "es" to "Spanish",
                "fr" to "French",
                "de" to "German",
                "pt" to "Portuguese",
                "ru" to "Russian",
                "ja" to "Japanese",
                "ko" to "Korean",
                "zh-Hans" to "Chinese (Simplified)",
                "ar" to "Arabic",
                "bn" to "Bengali",
                "te" to "Telugu",
                "mr" to "Marathi",
                "ta" to "Tamil",
                "ur" to "Urdu",
                "gu" to "Gujarati",
                "kn" to "Kannada",
                "ml" to "Malayalam",
                "pa" to "Punjabi",
                "it" to "Italian",
                "tr" to "Turkish",
                "id" to "Indonesian",
                "vi" to "Vietnamese"
            )

            val additionalTracks = mutableListOf<CaptionTrack>()
            for ((code, name) in popularTranslations) {
                if (!existingLangs.contains(code.lowercase())) {
                    val urlWithTlang = if (baseTrack.url.contains("tlang=")) {
                        baseTrack.url.replace(Regex("tlang=[^&]*"), "tlang=$code")
                    } else {
                        if (baseTrack.url.contains("?")) "${baseTrack.url}&tlang=$code" else "${baseTrack.url}?tlang=$code"
                    }
                    additionalTracks.add(
                        CaptionTrack(
                            languageTag = code,
                            displayName = "$name (Auto-translate)",
                            url = urlWithTlang,
                            isAutoGenerated = true
                        )
                    )
                }
            }
            return baseTracks + additionalTracks
        }
    }
}
