package com.videhub.viewmodel

import android.content.Context
import android.content.Intent
import android.widget.Toast
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.videhub.extractor.ExtractorHelper
import com.videhub.service.DownloadService
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import org.schabi.newpipe.extractor.stream.StreamInfo

class DownloadViewModel : ViewModel() {

    companion object {
        val activeDownloadUrls = java.util.Collections.synchronizedSet(mutableSetOf<String>())
        fun removeActiveDownload(url: String) {
            activeDownloadUrls.remove(url)
        }
    }

    fun cancelDownload(context: Context, notificationId: Int) {
        val intent = Intent(context, DownloadService::class.java).apply {
            action = "CANCEL_$notificationId"
        }
        androidx.core.content.ContextCompat.startForegroundService(context, intent)
        com.videhub.utils.DownloadProgressTracker.removeDownload(notificationId)
    }

    fun prepareAndStartDownload(
        context: Context,
        videoUrl: String,
        title: String,
        thumbnailUrl: String,
        streamInfo: StreamInfo?,
        resolution: String?,
        bitrate: Int?,
        formatName: String?,
        isAudioOnly: Boolean
    ) {
        viewModelScope.launch(Dispatchers.IO) {
            try {
                val db = com.videhub.data.AppDatabase.getDatabase(context)
                val isAlreadyDownloaded = db.downloadedVideoDao().isVideoDownloaded(videoUrl)

                if (isAlreadyDownloaded) {
                    showToast(context, "Already downloaded")
                    return@launch
                }

                val downloadKey = videoUrl
                if (activeDownloadUrls.contains(downloadKey)) {
                    showToast(context, "Already downloading")
                    return@launch
                }
                activeDownloadUrls.add(downloadKey)

                val fresh = ExtractorHelper.getStreamInfo(videoUrl) ?: streamInfo
                
                val intent = Intent(context, DownloadService::class.java).apply {
                    putExtra("title", title)
                    putExtra("videoId", videoUrl)
                    putExtra("thumbnailUrl", thumbnailUrl)
                    putExtra("channelName", streamInfo?.uploaderName ?: fresh?.uploaderName ?: "")
                    putExtra("viewCount", streamInfo?.viewCount ?: fresh?.viewCount ?: 0L)
                    putExtra("uploadDate", streamInfo?.textualUploadDate ?: fresh?.textualUploadDate ?: "")
                    putExtra("isAudioOnly", isAudioOnly)
                    
                    val subs = streamInfo?.subtitles ?: fresh?.subtitles
                    if (!subs.isNullOrEmpty()) {
                        val enSub = subs.find { it.languageTag.equals("en", true) } ?: subs.find { it.languageTag.startsWith("en", true) }
                        val nativeSub = subs.find { !it.languageTag.startsWith("en", true) } ?: subs.first()
                        putExtra("englishUrl", enSub?.content ?: "")
                        putExtra("nativeUrl", nativeSub?.content ?: "")
                        val subArr = org.json.JSONArray()
                        subs.forEach { s ->
                            val o = org.json.JSONObject()
                            o.put("url", s.content)
                            o.put("languageTag", s.languageTag)
                            o.put("isAutoGenerated", s.isAutoGenerated)
                            subArr.put(o)
                        }
                        putExtra("subtitlesJson", subArr.toString())
                    }
                    putExtra("description", streamInfo?.description?.content ?: fresh?.description?.content ?: "")
                }

                if (!isAudioOnly) {
                    val freshStream = if (resolution != null) {
                        fresh?.videoStreams?.find { it.getResolution() == resolution && !it.isVideoOnly }
                    } else {
                        fresh?.videoStreams?.filter { !it.content.isNullOrBlank() && !it.isVideoOnly }?.maxByOrNull { it.height ?: 0 }
                    }
                    if (freshStream != null && freshStream.content != null) {
                        intent.putExtra("url", freshStream.content ?: "")
                        val res = freshStream.resolution ?: "unknown"
                        intent.putExtra("suffix", "${res}.mp4")
                        startService(context, intent)
                    } else {
                        activeDownloadUrls.remove(downloadKey)
                        showToast(context, "Stream not available.")
                    }
                } else if (isAudioOnly) {
                    val freshAudio = fresh?.audioStreams?.find { !it.content.isNullOrBlank() && it.averageBitrate == bitrate && it.format?.name == formatName }
                        ?: fresh?.audioStreams?.find { !it.content.isNullOrBlank() && it.averageBitrate == bitrate }
                        ?: fresh?.audioStreams?.filter { !it.content.isNullOrBlank() }?.maxByOrNull { it.averageBitrate }
                        
                    if (freshAudio != null && freshAudio.content != null) {
                        intent.putExtra("url", freshAudio.content ?: "")
                        val suffix = if (freshAudio.format?.name?.contains("WEBM", ignoreCase = true) == true) "${bitrate}kbps.webm" else "${bitrate}kbps.m4a"
                        intent.putExtra("suffix", suffix)
                        startService(context, intent)
                    } else {
                        activeDownloadUrls.remove(downloadKey)
                        showToast(context, "Stream not available.")
                    }
                }
            } catch (e: Exception) {
                activeDownloadUrls.remove(videoUrl)
                showToast(context, "Could not prepare download: ${e.message}")
            }
        }
    }
    
    private fun startService(context: Context, intent: Intent) {
        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O) {
            context.startForegroundService(intent)
        } else {
            androidx.core.content.ContextCompat.startForegroundService(context, intent)
        }
    }
    
    private suspend fun showToast(context: Context, message: String) {
        withContext(Dispatchers.Main) {
            Toast.makeText(context, message, Toast.LENGTH_LONG).show()
        }
    }
}

